// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apiCatalogo.Context;

#nullable disable

namespace apiCatalogo.Migrations
{
    [DbContext(typeof(ApiCatalogoDbContext))]
    [Migration("20250516052116_normalizacao_dos_atributos")]
    partial class normalizacao_dos_atributos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("apiCatalogo.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("imUrl");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("nmCategoria");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Nome" }, "ix_categorias_nome")
                        .HasFilter("[nome] IS NOT NULL");

                    b.ToTable("tbCategorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagemUrl = "cosmeticos.jpg",
                            Nome = "Cosméticos"
                        },
                        new
                        {
                            Id = 2,
                            ImagemUrl = "eletronicos.jpg",
                            Nome = "Eletrônicos"
                        },
                        new
                        {
                            Id = 3,
                            ImagemUrl = "informatica.jpg",
                            Nome = "Informática"
                        },
                        new
                        {
                            Id = 4,
                            ImagemUrl = "moveis.jpg",
                            Nome = "Móveis"
                        },
                        new
                        {
                            Id = 5,
                            ImagemUrl = "eletrodomesticos.jpg",
                            Nome = "Eletrodomésticos"
                        },
                        new
                        {
                            Id = 6,
                            ImagemUrl = "bebidas.jpg",
                            Nome = "Bebidas"
                        },
                        new
                        {
                            Id = 7,
                            ImagemUrl = "alimentos.jpg",
                            Nome = "Alimentos"
                        },
                        new
                        {
                            Id = 8,
                            ImagemUrl = "limpeza.jpg",
                            Nome = "Limpeza"
                        },
                        new
                        {
                            Id = 9,
                            ImagemUrl = "brinquedos.jpg",
                            Nome = "Brinquedos"
                        },
                        new
                        {
                            Id = 10,
                            ImagemUrl = "livros.jpg",
                            Nome = "Livros"
                        },
                        new
                        {
                            Id = 11,
                            ImagemUrl = "papelaria.jpg",
                            Nome = "Papelaria"
                        },
                        new
                        {
                            Id = 12,
                            ImagemUrl = "ferramentas.jpg",
                            Nome = "Ferramentas"
                        },
                        new
                        {
                            Id = 13,
                            ImagemUrl = "esportes.jpg",
                            Nome = "Esportes"
                        },
                        new
                        {
                            Id = 14,
                            ImagemUrl = "moda-masculina.jpg",
                            Nome = "Moda Masculina"
                        },
                        new
                        {
                            Id = 15,
                            ImagemUrl = "moda-feminina.jpg",
                            Nome = "Moda Feminina"
                        },
                        new
                        {
                            Id = 16,
                            ImagemUrl = "calcados.jpg",
                            Nome = "Calçados"
                        },
                        new
                        {
                            Id = 17,
                            ImagemUrl = "acessorios.jpg",
                            Nome = "Acessórios"
                        },
                        new
                        {
                            Id = 18,
                            ImagemUrl = "jardim.jpg",
                            Nome = "Jardim"
                        },
                        new
                        {
                            Id = 19,
                            ImagemUrl = "automotivo.jpg",
                            Nome = "Automotivo"
                        },
                        new
                        {
                            Id = 20,
                            ImagemUrl = "petshop.jpg",
                            Nome = "Pet Shop"
                        });
                });

            modelBuilder.Entity("apiCatalogo.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("categoriaId");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2025, 5, 16, 2, 21, 14, 924, DateTimeKind.Local).AddTicks(7314))
                        .HasColumnName("dtCadastro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("dsProduto");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("imUrl");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("nmProduto");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("int")
                        .HasColumnName("qtEstoque");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("vlProduto");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex(new[] { "Descricao" }, "ix_produtos_descricao")
                        .HasFilter("[nome] IS NOT NULL");

                    b.HasIndex(new[] { "Nome" }, "ix_produtos_nome")
                        .HasFilter("[nome] IS NOT NULL");

                    b.ToTable("tbProdutos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descricao = "Creme de barbear fragrância de menta",
                            ImagemUrl = "creme-barbear.jpg",
                            Nome = "Creme de Barbear",
                            QuantidadeEstoque = 50,
                            Valor = 68.50m
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            Descricao = "Hidratante para pele oleosa 50ml",
                            ImagemUrl = "hidratante-facial.jpg",
                            Nome = "Hidratante Facial",
                            QuantidadeEstoque = 30,
                            Valor = 89.90m
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 1,
                            Descricao = "Shampoo para controle de caspa 300ml",
                            ImagemUrl = "shampoo-anticaspa.jpg",
                            Nome = "Shampoo Anticaspa",
                            QuantidadeEstoque = 45,
                            Valor = 32.75m
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 1,
                            Descricao = "Batom matte de longa duração",
                            ImagemUrl = "batom-matte.jpg",
                            Nome = "Batom Matte",
                            QuantidadeEstoque = 60,
                            Valor = 45.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 1,
                            Descricao = "Máscara para cílios à prova d'água",
                            ImagemUrl = "mascara-cilios.jpg",
                            Nome = "Máscara de Cílios",
                            QuantidadeEstoque = 35,
                            Valor = 39.90m
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 1,
                            Descricao = "Perfume 100ml fragrância amadeirada",
                            ImagemUrl = "perfume-masculino.jpg",
                            Nome = "Perfume Masculino",
                            QuantidadeEstoque = 25,
                            Valor = 199.90m
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 1,
                            Descricao = "Desodorante antitranspirante 50ml",
                            ImagemUrl = "desodorante-rollon.jpg",
                            Nome = "Desodorante Roll On",
                            QuantidadeEstoque = 70,
                            Valor = 18.50m
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 1,
                            Descricao = "Sabonete líquido facial 200ml",
                            ImagemUrl = "sabonete-liquido.jpg",
                            Nome = "Sabonete Líquido",
                            QuantidadeEstoque = 40,
                            Valor = 28.75m
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 1,
                            Descricao = "Protetor solar facial oil free",
                            ImagemUrl = "protetor-solar.jpg",
                            Nome = "Protetor Solar FPS 50",
                            QuantidadeEstoque = 55,
                            Valor = 79.90m
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 1,
                            Descricao = "Condicionador para cabelos danificados",
                            ImagemUrl = "condicionador.jpg",
                            Nome = "Condicionador Reparador",
                            QuantidadeEstoque = 38,
                            Valor = 42.50m
                        },
                        new
                        {
                            Id = 11,
                            CategoriaId = 1,
                            Descricao = "Esmalte de longa duração",
                            ImagemUrl = "esmalte-vermelho.jpg",
                            Nome = "Esmalte Vermelho",
                            QuantidadeEstoque = 85,
                            Valor = 12.90m
                        },
                        new
                        {
                            Id = 12,
                            CategoriaId = 1,
                            Descricao = "Demaquilante para olhos sensíveis",
                            ImagemUrl = "demaquilante.jpg",
                            Nome = "Demaquilante Bifásico",
                            QuantidadeEstoque = 28,
                            Valor = 34.90m
                        },
                        new
                        {
                            Id = 13,
                            CategoriaId = 1,
                            Descricao = "Creme hidratante para mãos 75ml",
                            ImagemUrl = "creme-maos.jpg",
                            Nome = "Creme para Mãos",
                            QuantidadeEstoque = 42,
                            Valor = 27.50m
                        },
                        new
                        {
                            Id = 14,
                            CategoriaId = 1,
                            Descricao = "Tônico adstringente para pele oleosa",
                            ImagemUrl = "tonico-facial.jpg",
                            Nome = "Tônico Facial",
                            QuantidadeEstoque = 33,
                            Valor = 65.00m
                        },
                        new
                        {
                            Id = 15,
                            CategoriaId = 1,
                            Descricao = "Máscara de argila para limpeza profunda",
                            ImagemUrl = "mascara-facial.jpg",
                            Nome = "Máscara Facial",
                            QuantidadeEstoque = 47,
                            Valor = 49.90m
                        },
                        new
                        {
                            Id = 16,
                            CategoriaId = 1,
                            Descricao = "Pó compacto matte cor bege médio",
                            ImagemUrl = "po-compacto.jpg",
                            Nome = "Pó Compacto",
                            QuantidadeEstoque = 29,
                            Valor = 58.75m
                        },
                        new
                        {
                            Id = 17,
                            CategoriaId = 1,
                            Descricao = "Delineador de precisão à prova d'água",
                            ImagemUrl = "delineador.jpg",
                            Nome = "Delineador Líquido",
                            QuantidadeEstoque = 51,
                            Valor = 36.90m
                        },
                        new
                        {
                            Id = 18,
                            CategoriaId = 1,
                            Descricao = "Água micelar 400ml para limpeza facial",
                            ImagemUrl = "agua-micelar.jpg",
                            Nome = "Água Micelar",
                            QuantidadeEstoque = 36,
                            Valor = 72.50m
                        },
                        new
                        {
                            Id = 19,
                            CategoriaId = 1,
                            Descricao = "Serum anti-idade com vitamina C",
                            ImagemUrl = "serum-facial.jpg",
                            Nome = "Serum Facial",
                            QuantidadeEstoque = 22,
                            Valor = 115.00m
                        },
                        new
                        {
                            Id = 20,
                            CategoriaId = 1,
                            Descricao = "Loção calmante para após o barbear",
                            ImagemUrl = "pos-barba.jpg",
                            Nome = "Loção Pós-Barba",
                            QuantidadeEstoque = 43,
                            Valor = 54.90m
                        },
                        new
                        {
                            Id = 21,
                            CategoriaId = 2,
                            Descricao = "Fone sem fio com cancelamento de ruído",
                            ImagemUrl = "fone-bluetooth.jpg",
                            Nome = "Fone Bluetooth",
                            QuantidadeEstoque = 25,
                            Valor = 299.90m
                        },
                        new
                        {
                            Id = 22,
                            CategoriaId = 2,
                            Descricao = "Relógio inteligente com monitor cardíaco",
                            ImagemUrl = "smartwatch.jpg",
                            Nome = "Smartwatch",
                            QuantidadeEstoque = 15,
                            Valor = 799.00m
                        },
                        new
                        {
                            Id = 23,
                            CategoriaId = 2,
                            Descricao = "Caixa de som à prova d'água 20W",
                            ImagemUrl = "caixa-som.jpg",
                            Nome = "Caixa de Som Portátil",
                            QuantidadeEstoque = 20,
                            Valor = 349.90m
                        },
                        new
                        {
                            Id = 24,
                            CategoriaId = 2,
                            Descricao = "Tablet 128GB RAM 4GB",
                            ImagemUrl = "tablet.jpg",
                            Nome = "Tablet 10 Polegadas",
                            QuantidadeEstoque = 12,
                            Valor = 1299.00m
                        },
                        new
                        {
                            Id = 25,
                            CategoriaId = 2,
                            Descricao = "Power bank 10000mAh",
                            ImagemUrl = "powerbank.jpg",
                            Nome = "Carregador Portátil",
                            QuantidadeEstoque = 35,
                            Valor = 89.90m
                        },
                        new
                        {
                            Id = 26,
                            CategoriaId = 2,
                            Descricao = "Webcam com microfone integrado",
                            ImagemUrl = "webcam.jpg",
                            Nome = "Webcam Full HD",
                            QuantidadeEstoque = 18,
                            Valor = 199.90m
                        },
                        new
                        {
                            Id = 27,
                            CategoriaId = 2,
                            Descricao = "Teclado gamer RGB switches azuis",
                            ImagemUrl = "teclado-mecanico.jpg",
                            Nome = "Teclado Mecânico",
                            QuantidadeEstoque = 14,
                            Valor = 279.90m
                        },
                        new
                        {
                            Id = 28,
                            CategoriaId = 2,
                            Descricao = "Mouse óptico 1600DPI",
                            ImagemUrl = "mouse-semfio.jpg",
                            Nome = "Mouse Sem Fio",
                            QuantidadeEstoque = 30,
                            Valor = 59.90m
                        },
                        new
                        {
                            Id = 29,
                            CategoriaId = 2,
                            Descricao = "Monitor Full HD IPS",
                            ImagemUrl = "monitor.jpg",
                            Nome = "Monitor 24 Polegadas",
                            QuantidadeEstoque = 8,
                            Valor = 899.00m
                        },
                        new
                        {
                            Id = 30,
                            CategoriaId = 2,
                            Descricao = "HD externo USB 3.0",
                            ImagemUrl = "hd-externo.jpg",
                            Nome = "HD Externo 1TB",
                            QuantidadeEstoque = 22,
                            Valor = 299.90m
                        },
                        new
                        {
                            Id = 31,
                            CategoriaId = 2,
                            Descricao = "Leitor de e-books 6 polegadas",
                            ImagemUrl = "kindle.jpg",
                            Nome = "Kindle 10a Geração",
                            QuantidadeEstoque = 17,
                            Valor = 399.00m
                        },
                        new
                        {
                            Id = 32,
                            CategoriaId = 2,
                            Descricao = "Drone com câmera 4K",
                            ImagemUrl = "drone.jpg",
                            Nome = "Drone DJI Mini",
                            QuantidadeEstoque = 5,
                            Valor = 2499.00m
                        },
                        new
                        {
                            Id = 33,
                            CategoriaId = 2,
                            Descricao = "Fita de LED 5m controlável por app",
                            ImagemUrl = "fita-led.jpg",
                            Nome = "Fita LED RGB",
                            QuantidadeEstoque = 28,
                            Valor = 79.90m
                        },
                        new
                        {
                            Id = 34,
                            CategoriaId = 2,
                            Descricao = "Console retro com 200 jogos",
                            ImagemUrl = "console-retro.jpg",
                            Nome = "Console Portátil",
                            QuantidadeEstoque = 10,
                            Valor = 199.90m
                        },
                        new
                        {
                            Id = 35,
                            CategoriaId = 2,
                            Descricao = "Projetor portátil 1080p",
                            ImagemUrl = "projetor.jpg",
                            Nome = "Projetor Mini",
                            QuantidadeEstoque = 7,
                            Valor = 599.00m
                        },
                        new
                        {
                            Id = 36,
                            CategoriaId = 2,
                            Descricao = "TV 4K Android TV",
                            ImagemUrl = "smarttv.jpg",
                            Nome = "Smart TV 50 Polegadas",
                            QuantidadeEstoque = 6,
                            Valor = 2399.00m
                        },
                        new
                        {
                            Id = 37,
                            CategoriaId = 2,
                            Descricao = "Soundbar com subwoofer sem fio",
                            ImagemUrl = "soundbar.jpg",
                            Nome = "Soundbar 2.1",
                            QuantidadeEstoque = 9,
                            Valor = 499.00m
                        },
                        new
                        {
                            Id = 38,
                            CategoriaId = 2,
                            Descricao = "Câmera fotográfica com impressão",
                            ImagemUrl = "camera-instantanea.jpg",
                            Nome = "Câmera Instantânea",
                            QuantidadeEstoque = 13,
                            Valor = 349.90m
                        },
                        new
                        {
                            Id = 39,
                            CategoriaId = 2,
                            Descricao = "Roteador dual band 5Ghz",
                            ImagemUrl = "roteador.jpg",
                            Nome = "Roteador Wi-Fi 6",
                            QuantidadeEstoque = 11,
                            Valor = 399.00m
                        },
                        new
                        {
                            Id = 40,
                            CategoriaId = 2,
                            Descricao = "Pen drive USB 3.2",
                            ImagemUrl = "pendrive.jpg",
                            Nome = "Pen Drive 128GB",
                            QuantidadeEstoque = 40,
                            Valor = 59.90m
                        },
                        new
                        {
                            Id = 41,
                            CategoriaId = 3,
                            Descricao = "Notebook 8GB RAM SSD 256GB",
                            ImagemUrl = "notebook-i5.jpg",
                            Nome = "Notebook i5",
                            QuantidadeEstoque = 10,
                            Valor = 3299.00m
                        },
                        new
                        {
                            Id = 42,
                            CategoriaId = 3,
                            Descricao = "Mouse com 6 botões programáveis",
                            ImagemUrl = "mouse-gamer.jpg",
                            Nome = "Mouse Gamer",
                            QuantidadeEstoque = 30,
                            Valor = 159.90m
                        },
                        new
                        {
                            Id = 43,
                            CategoriaId = 3,
                            Descricao = "Teclado slim Bluetooth",
                            ImagemUrl = "teclado-semfio.jpg",
                            Nome = "Teclado Sem Fio",
                            QuantidadeEstoque = 25,
                            Valor = 129.90m
                        },
                        new
                        {
                            Id = 44,
                            CategoriaId = 3,
                            Descricao = "Monitor gamer 144Hz",
                            ImagemUrl = "monitor-gamer.jpg",
                            Nome = "Monitor 27''",
                            QuantidadeEstoque = 8,
                            Valor = 1599.00m
                        },
                        new
                        {
                            Id = 45,
                            CategoriaId = 3,
                            Descricao = "SSD NVMe Leitura 3500MB/s",
                            ImagemUrl = "ssd.jpg",
                            Nome = "SSD 512GB",
                            QuantidadeEstoque = 18,
                            Valor = 299.90m
                        },
                        new
                        {
                            Id = 46,
                            CategoriaId = 3,
                            Descricao = "Webcam Full HD com microfone",
                            ImagemUrl = "webcam-hd.jpg",
                            Nome = "Webcam HD",
                            QuantidadeEstoque = 14,
                            Valor = 189.90m
                        },
                        new
                        {
                            Id = 47,
                            CategoriaId = 3,
                            Descricao = "Impressora jato de tinta",
                            ImagemUrl = "impressora.jpg",
                            Nome = "Impressora Multifuncional",
                            QuantidadeEstoque = 9,
                            Valor = 499.00m
                        },
                        new
                        {
                            Id = 48,
                            CategoriaId = 3,
                            Descricao = "Headset com microfone retrátil",
                            ImagemUrl = "headset-gamer.jpg",
                            Nome = "Headset Gamer",
                            QuantidadeEstoque = 12,
                            Valor = 229.90m
                        },
                        new
                        {
                            Id = 49,
                            CategoriaId = 3,
                            Descricao = "Hub USB-C 4 portas",
                            ImagemUrl = "hub-usb.jpg",
                            Nome = "Hub USB",
                            QuantidadeEstoque = 30,
                            Valor = 79.90m
                        },
                        new
                        {
                            Id = 50,
                            CategoriaId = 3,
                            Descricao = "Notebook RTX 3050 16GB RAM",
                            ImagemUrl = "notebook-gamer.jpg",
                            Nome = "Notebook Gamer",
                            QuantidadeEstoque = 5,
                            Valor = 6299.00m
                        },
                        new
                        {
                            Id = 51,
                            CategoriaId = 3,
                            Descricao = "Mouse pad 90x40cm antiderrapante",
                            ImagemUrl = "mousepad.jpg",
                            Nome = "Mouse Pad Grande",
                            QuantidadeEstoque = 40,
                            Valor = 49.90m
                        },
                        new
                        {
                            Id = 52,
                            CategoriaId = 3,
                            Descricao = "Cadeira ergonômica com apoio lombar",
                            ImagemUrl = "cadeira-gamer.jpg",
                            Nome = "Cadeira Gamer",
                            QuantidadeEstoque = 7,
                            Valor = 1299.00m
                        },
                        new
                        {
                            Id = 53,
                            CategoriaId = 3,
                            Descricao = "Roteador dual band AC1200",
                            ImagemUrl = "roteador-wifi.jpg",
                            Nome = "Roteador Wi-Fi",
                            QuantidadeEstoque = 15,
                            Valor = 249.90m
                        },
                        new
                        {
                            Id = 54,
                            CategoriaId = 3,
                            Descricao = "Pendrive USB 3.0",
                            ImagemUrl = "pendrive-256gb.jpg",
                            Nome = "Pendrive 256GB",
                            QuantidadeEstoque = 22,
                            Valor = 99.90m
                        },
                        new
                        {
                            Id = 55,
                            CategoriaId = 3,
                            Descricao = "HD externo USB 3.2",
                            ImagemUrl = "hd-externo-2tb.jpg",
                            Nome = "HD Externo 2TB",
                            QuantidadeEstoque = 11,
                            Valor = 499.90m
                        },
                        new
                        {
                            Id = 56,
                            CategoriaId = 3,
                            Descricao = "Cooler com 3 ventoinhas",
                            ImagemUrl = "cooler-notebook.jpg",
                            Nome = "Cooler para Notebook",
                            QuantidadeEstoque = 19,
                            Valor = 89.90m
                        },
                        new
                        {
                            Id = 57,
                            CategoriaId = 3,
                            Descricao = "Tablet digitalizador A5",
                            ImagemUrl = "mesa-digitalizadora.jpg",
                            Nome = "Mesa Digitalizadora",
                            QuantidadeEstoque = 8,
                            Valor = 399.00m
                        },
                        new
                        {
                            Id = 58,
                            CategoriaId = 3,
                            Descricao = "Fonte universal 65W",
                            ImagemUrl = "fonte-notebook.jpg",
                            Nome = "Fonte Notebook",
                            QuantidadeEstoque = 13,
                            Valor = 119.90m
                        },
                        new
                        {
                            Id = 59,
                            CategoriaId = 3,
                            Descricao = "Seletor HDMI 4 portas",
                            ImagemUrl = "switch-hdmi.jpg",
                            Nome = "Switch HDMI",
                            QuantidadeEstoque = 10,
                            Valor = 159.90m
                        },
                        new
                        {
                            Id = 60,
                            CategoriaId = 3,
                            Descricao = "Kit sem fio 2.4GHz",
                            ImagemUrl = "kit-teclado-mouse.jpg",
                            Nome = "Kit Teclado e Mouse",
                            QuantidadeEstoque = 25,
                            Valor = 149.90m
                        },
                        new
                        {
                            Id = 61,
                            CategoriaId = 4,
                            Descricao = "Sofá retrátil em couro sintético",
                            ImagemUrl = "sofa-3lugares.jpg",
                            Nome = "Sofá 3 Lugares",
                            QuantidadeEstoque = 5,
                            Valor = 1899.00m
                        },
                        new
                        {
                            Id = 62,
                            CategoriaId = 4,
                            Descricao = "Cadeira ergonômica com regulagem de altura",
                            ImagemUrl = "cadeira-escritorio.jpg",
                            Nome = "Cadeira de Escritório",
                            QuantidadeEstoque = 12,
                            Valor = 499.90m
                        },
                        new
                        {
                            Id = 63,
                            CategoriaId = 4,
                            Descricao = "Mesa de centro em madeira maciça",
                            ImagemUrl = "mesa-centro.jpg",
                            Nome = "Mesa de Centro",
                            QuantidadeEstoque = 8,
                            Valor = 349.90m
                        },
                        new
                        {
                            Id = 64,
                            CategoriaId = 4,
                            Descricao = "Estante 5 prateleiras 1,80m",
                            ImagemUrl = "estante-livros.jpg",
                            Nome = "Estante para Livros",
                            QuantidadeEstoque = 6,
                            Valor = 429.00m
                        },
                        new
                        {
                            Id = 65,
                            CategoriaId = 4,
                            Descricao = "Cama box com cabeceira estofada",
                            ImagemUrl = "cama-casal.jpg",
                            Nome = "Cama Box Casal",
                            QuantidadeEstoque = 9,
                            Valor = 899.00m
                        },
                        new
                        {
                            Id = 66,
                            CategoriaId = 4,
                            Descricao = "Guarda-roupa espelhado grande",
                            ImagemUrl = "guarda-roupa.jpg",
                            Nome = "Guarda-Roupa 6 Portas",
                            QuantidadeEstoque = 5,
                            Valor = 1299.00m
                        },
                        new
                        {
                            Id = 67,
                            CategoriaId = 4,
                            Descricao = "Rack moderno para TV até 65''",
                            ImagemUrl = "rack-tv.jpg",
                            Nome = "Rack para TV",
                            QuantidadeEstoque = 7,
                            Valor = 579.90m
                        },
                        new
                        {
                            Id = 68,
                            CategoriaId = 4,
                            Descricao = "Banqueta alta com encosto",
                            ImagemUrl = "banqueta-bar.jpg",
                            Nome = "Banqueta de Bar",
                            QuantidadeEstoque = 15,
                            Valor = 229.90m
                        },
                        new
                        {
                            Id = 69,
                            CategoriaId = 4,
                            Descricao = "Cômoda em MDF 80cm",
                            ImagemUrl = "comoda.jpg",
                            Nome = "Cômoda 4 Gavetas",
                            QuantidadeEstoque = 11,
                            Valor = 399.00m
                        },
                        new
                        {
                            Id = 70,
                            CategoriaId = 4,
                            Descricao = "Poltrona de descanso reclinável",
                            ImagemUrl = "poltrona.jpg",
                            Nome = "Poltrona Reclinável",
                            QuantidadeEstoque = 4,
                            Valor = 699.00m
                        },
                        new
                        {
                            Id = 71,
                            CategoriaId = 4,
                            Descricao = "Painel flutuante para TV e objetos",
                            ImagemUrl = "painel-tv.jpg",
                            Nome = "Painel para TV",
                            QuantidadeEstoque = 8,
                            Valor = 429.90m
                        },
                        new
                        {
                            Id = 72,
                            CategoriaId = 4,
                            Descricao = "Criado mudo com gaveta",
                            ImagemUrl = "criado-mudo.jpg",
                            Nome = "Criado Mudo",
                            QuantidadeEstoque = 14,
                            Valor = 179.90m
                        },
                        new
                        {
                            Id = 73,
                            CategoriaId = 4,
                            Descricao = "Sofá que vira cama de solteiro",
                            ImagemUrl = "sofa-cama.jpg",
                            Nome = "Sofá-cama",
                            QuantidadeEstoque = 6,
                            Valor = 999.00m
                        },
                        new
                        {
                            Id = 74,
                            CategoriaId = 4,
                            Descricao = "Espreguiçadeira para jardim",
                            ImagemUrl = "espreguicadeira.jpg",
                            Nome = "Espreguiçadeira",
                            QuantidadeEstoque = 10,
                            Valor = 299.90m
                        },
                        new
                        {
                            Id = 75,
                            CategoriaId = 4,
                            Descricao = "Mesa para computador 120cm",
                            ImagemUrl = "mesa-computador.jpg",
                            Nome = "Mesa de Computador",
                            QuantidadeEstoque = 9,
                            Valor = 349.00m
                        },
                        new
                        {
                            Id = 76,
                            CategoriaId = 4,
                            Descricao = "Banco estreito para entrada",
                            ImagemUrl = "banco-corredor.jpg",
                            Nome = "Banco de Corredor",
                            QuantidadeEstoque = 13,
                            Valor = 159.90m
                        },
                        new
                        {
                            Id = 77,
                            CategoriaId = 4,
                            Descricao = "Aparador de cozinha 2 portas",
                            ImagemUrl = "aparador.jpg",
                            Nome = "Aparador",
                            QuantidadeEstoque = 7,
                            Valor = 279.90m
                        },
                        new
                        {
                            Id = 78,
                            CategoriaId = 4,
                            Descricao = "Cadeira de balanço em vime",
                            ImagemUrl = "cadeira-balanco.jpg",
                            Nome = "Cadeira de Balanço",
                            QuantidadeEstoque = 5,
                            Valor = 459.00m
                        },
                        new
                        {
                            Id = 79,
                            CategoriaId = 4,
                            Descricao = "Armário suspenso 60cm",
                            ImagemUrl = "armario-cozinha.jpg",
                            Nome = "Armário para Cozinha",
                            QuantidadeEstoque = 8,
                            Valor = 329.90m
                        },
                        new
                        {
                            Id = 80,
                            CategoriaId = 4,
                            Descricao = "Mesa e 4 cadeiras para jardim",
                            ImagemUrl = "conjunto-jardim.jpg",
                            Nome = "Conjunto de Jardim",
                            QuantidadeEstoque = 4,
                            Valor = 899.00m
                        },
                        new
                        {
                            Id = 81,
                            CategoriaId = 5,
                            Descricao = "Geladeira duplex 375L branca",
                            ImagemUrl = "geladeira-frostfree.jpg",
                            Nome = "Geladeira Frost Free",
                            QuantidadeEstoque = 7,
                            Valor = 2899.00m
                        },
                        new
                        {
                            Id = 82,
                            CategoriaId = 5,
                            Descricao = "Fogão inox com forno elétrico",
                            ImagemUrl = "fogao-5bocas.jpg",
                            Nome = "Fogão 5 Bocas",
                            QuantidadeEstoque = 12,
                            Valor = 1599.90m
                        },
                        new
                        {
                            Id = 83,
                            CategoriaId = 5,
                            Descricao = "Lavadora 12kg 15 programas",
                            ImagemUrl = "maquina-lavar.jpg",
                            Nome = "Máquina de Lavar",
                            QuantidadeEstoque = 9,
                            Valor = 2199.00m
                        },
                        new
                        {
                            Id = 84,
                            CategoriaId = 5,
                            Descricao = "Micro-ondas grill 1100W",
                            ImagemUrl = "microondas.jpg",
                            Nome = "Micro-ondas 32L",
                            QuantidadeEstoque = 15,
                            Valor = 599.90m
                        },
                        new
                        {
                            Id = 85,
                            CategoriaId = 5,
                            Descricao = "Lava-louças 8 serviços",
                            ImagemUrl = "lava-loucas.jpg",
                            Nome = "Lava-Louças",
                            QuantidadeEstoque = 5,
                            Valor = 2499.00m
                        },
                        new
                        {
                            Id = 86,
                            CategoriaId = 5,
                            Descricao = "Ar condicionado 9000 BTUs",
                            ImagemUrl = "ar-condicionado.jpg",
                            Nome = "Ar Condicionado Split",
                            QuantidadeEstoque = 8,
                            Valor = 1899.00m
                        },
                        new
                        {
                            Id = 87,
                            CategoriaId = 5,
                            Descricao = "Purificador com geladeira",
                            ImagemUrl = "purificador.jpg",
                            Nome = "Purificador de Água",
                            QuantidadeEstoque = 14,
                            Valor = 799.90m
                        },
                        new
                        {
                            Id = 88,
                            CategoriaId = 5,
                            Descricao = "Cooktop de vidro 220V",
                            ImagemUrl = "cooktop.jpg",
                            Nome = "Cooktop 4 Bocas",
                            QuantidadeEstoque = 10,
                            Valor = 899.00m
                        },
                        new
                        {
                            Id = 89,
                            CategoriaId = 5,
                            Descricao = "Ventilador 3 pás 110V",
                            ImagemUrl = "ventilador-teto.jpg",
                            Nome = "Ventilador de Teto",
                            QuantidadeEstoque = 18,
                            Valor = 249.90m
                        },
                        new
                        {
                            Id = 90,
                            CategoriaId = 5,
                            Descricao = "Secadora 8kg capacidade",
                            ImagemUrl = "secadora.jpg",
                            Nome = "Secadora de Roupas",
                            QuantidadeEstoque = 6,
                            Valor = 1799.00m
                        },
                        new
                        {
                            Id = 91,
                            CategoriaId = 5,
                            Descricao = "Aspirador vertical sem fio",
                            ImagemUrl = "aspirador.jpg",
                            Nome = "Aspirador de Pó",
                            QuantidadeEstoque = 20,
                            Valor = 399.90m
                        },
                        new
                        {
                            Id = 92,
                            CategoriaId = 5,
                            Descricao = "Ferro 1800W com base cerâmica",
                            ImagemUrl = "ferro-vapor.jpg",
                            Nome = "Ferro a Vapor",
                            QuantidadeEstoque = 25,
                            Valor = 129.90m
                        },
                        new
                        {
                            Id = 93,
                            CategoriaId = 5,
                            Descricao = "Forno 35L com timer digital",
                            ImagemUrl = "forno-eletrico.jpg",
                            Nome = "Forno Elétrico",
                            QuantidadeEstoque = 11,
                            Valor = 349.90m
                        },
                        new
                        {
                            Id = 94,
                            CategoriaId = 5,
                            Descricao = "Liquidificador 800W 6 velocidades",
                            ImagemUrl = "liquidificador.jpg",
                            Nome = "Liquidificador",
                            QuantidadeEstoque = 22,
                            Valor = 179.90m
                        },
                        new
                        {
                            Id = 95,
                            CategoriaId = 5,
                            Descricao = "Batedeira 500W 5 velocidades",
                            ImagemUrl = "batedeira.jpg",
                            Nome = "Batedeira Planetária",
                            QuantidadeEstoque = 13,
                            Valor = 299.90m
                        },
                        new
                        {
                            Id = 96,
                            CategoriaId = 5,
                            Descricao = "Cafeteira 15 xícaras programável",
                            ImagemUrl = "cafeteira.jpg",
                            Nome = "Cafeteira Elétrica",
                            QuantidadeEstoque = 17,
                            Valor = 199.90m
                        },
                        new
                        {
                            Id = 97,
                            CategoriaId = 5,
                            Descricao = "Grill dupla face 2000W",
                            ImagemUrl = "grill.jpg",
                            Nome = "Grill Elétrico",
                            QuantidadeEstoque = 9,
                            Valor = 229.90m
                        },
                        new
                        {
                            Id = 98,
                            CategoriaId = 5,
                            Descricao = "Processador 500W 3 acessórios",
                            ImagemUrl = "processador.jpg",
                            Nome = "Processador de Alimentos",
                            QuantidadeEstoque = 12,
                            Valor = 279.90m
                        },
                        new
                        {
                            Id = 99,
                            CategoriaId = 5,
                            Descricao = "Depurador com filtro HEPA",
                            ImagemUrl = "depurador.jpg",
                            Nome = "Depurador de Ar",
                            QuantidadeEstoque = 7,
                            Valor = 599.00m
                        },
                        new
                        {
                            Id = 100,
                            CategoriaId = 5,
                            Descricao = "Robô aspirador inteligente",
                            ImagemUrl = "robo-aspirador.jpg",
                            Nome = "Robô Aspirador",
                            QuantidadeEstoque = 5,
                            Valor = 1299.00m
                        });
                });

            modelBuilder.Entity("apiCatalogo.Models.Produto", b =>
                {
                    b.HasOne("apiCatalogo.Models.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categorias_categoriasId");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("apiCatalogo.Models.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
